// External watchdog sidecar (v0.1.341).
//
// Why this exists: a real-world incident — captured by the v0.1.340
// heartbeat + a live `sample(1)` of the wedged process — proved the
// macOS wake-hang is a MAIN-PROCESS JavaScript busy-spin: pid alive,
// STAT=R (burning CPU), 100% of samples in one identical JIT'd JS stack,
// no native/PGlite frames. While the main JS thread spins, NOTHING
// in-process can run — not the heartbeat timer, not the powerMonitor
// "resume" handler, not the auto-updater, not the v0.1.335 renderer
// recovery. So recovery is only possible from OUTSIDE the wedged process.
//
// This module spawns a tiny detached Node sidecar (running under the
// Electron binary via ELECTRON_RUN_AS_NODE) that has its own event loop,
// immune to main's freeze. It watches the heartbeat file the file-logger
// truncates every 2s and, if the heartbeat stops ADVANCING while the
// watchdog itself is still ticking (i.e. the machine is awake but main is
// wedged), it SIGKILLs main and relaunches the app.
//
// Sleep false-positive avoidance: during system sleep the watchdog is
// ALSO suspended, so its timer doesn't fire. We therefore never trust
// "heartbeat age" (which would include the whole sleep duration). We
// only declare a wedge when the heartbeat value fails to change across
// several consecutive watchdog ticks of REAL awake time. A large gap
// between two ticks means we were asleep → we reset the grace window so
// main gets a fresh chance to resume ticking after wake.

import { app } from "electron";
import { spawn } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getHeartbeatPath, getLogDir } from "./file-logger";

let started = false;

/**
 * v0.1.351 — Pfad des "Update läuft"-Flags. Wird vom Install-Handler
 * (index.ts updater:install) geschrieben, bevor quitAndInstall feuert,
 * und vom Watchdog bei jedem Tick geprüft. Liegt das Flag, beendet sich
 * der Watchdog OHNE Relaunch — sonst würde er den während des Updates
 * sterbenden/eingefrorenen Main-Prozess als "wedged" werten und AVA
 * mitten in der Installation neu starten (auf Windows → NSIS-Fehler
 * "AVA kann nicht geschlossen werden").
 */
export function getUpdatingFlagPath(): string {
  return join(app.getPath("userData"), "ava-updating.flag");
}

/** Schreibt das Update-Flag synchron. Idempotent. */
export function writeUpdatingFlag(): void {
  const p = getUpdatingFlagPath();
  mkdirSync(app.getPath("userData"), { recursive: true });
  writeFileSync(p, String(Date.now()), "utf8");
}

// The watchdog program text. Materialised to <userData>/ava-watchdog.cjs
// at boot and run as a standalone Node script — it uses only node
// builtins (fs, child_process), so it needs no bundling and no
// electron-builder packaging changes. String.raw keeps the embedded
// `\n` escapes literal in the generated file. (No `${}` interpolation
// inside — values are passed via env, not baked in.)
const WATCHDOG_SOURCE = String.raw`"use strict";
// AVA external watchdog — auto-generated by main/watchdog.ts. Do not edit.
const fs = require("node:fs");
const { spawn } = require("node:child_process");

const HEARTBEAT = process.env.AVA_WD_HEARTBEAT || "";
const MAIN_PID = parseInt(process.env.AVA_WD_MAIN_PID || "0", 10);
const APP_PATH = process.env.AVA_WD_APP_PATH || "";
const LOG = process.env.AVA_WD_LOG || "";
const UPDATING_FLAG = process.env.AVA_WD_UPDATING_FLAG || "";

const TICK_MS = 5000;     // how often we check
const STALE_MS = 20000;   // heartbeat must advance within this much AWAKE time
const WAKE_GAP_MS = 15000; // tick gap bigger than this == we were asleep

function log(msg) {
  const line = new Date().toISOString() + " [watchdog] " + msg + "\n";
  try { if (LOG) fs.appendFileSync(LOG, line); } catch (e) {}
  try { process.stdout.write(line); } catch (e) {}
}

function mainAlive() {
  if (!MAIN_PID) return false;
  try { process.kill(MAIN_PID, 0); return true; } catch (e) { return false; }
}

function readHeartbeat() {
  try { return fs.readFileSync(HEARTBEAT, "utf8").trim(); } catch (e) { return null; }
}

function relaunch() {
  log("relaunching app: " + APP_PATH);
  try {
    if (process.platform === "darwin") {
      spawn("open", [APP_PATH], { detached: true, stdio: "ignore" }).unref();
    } else {
      spawn(APP_PATH, [], { detached: true, stdio: "ignore" }).unref();
    }
  } catch (e) { log("relaunch failed: " + e); }
}

let lastValue = readHeartbeat();
let unchangedSince = Date.now();
let lastTick = Date.now();
let recovering = false;

log("started; main pid=" + MAIN_PID + " heartbeat=" + HEARTBEAT);

const timer = setInterval(function () {
  const now = Date.now();
  const gap = now - lastTick;
  lastTick = now;

  // v0.1.351 — Update läuft? Dann NICHT relaunchen. Der Install-Handler
  // schreibt dieses Flag vor quitAndInstall. Ohne diese Prüfung würde
  // der Watchdog den während des Updates sterbenden/eingefrorenen
  // Main-Prozess als "wedged" werten und AVA mitten in der Installation
  // neu starten (Windows: NSIS-Fehler "kann nicht geschlossen werden").
  if (UPDATING_FLAG) {
    try {
      if (fs.existsSync(UPDATING_FLAG)) {
        log("update in progress (flag present) -> exiting watchdog, no relaunch");
        clearInterval(timer);
        process.exit(0);
        return;
      }
    } catch (e) {}
  }

  // Clean quit of main -> our job is done. A fresh main spawns a fresh
  // watchdog, so exiting here avoids relaunching on top of a normal quit.
  if (!mainAlive()) {
    log("main pid " + MAIN_PID + " gone -> exiting watchdog");
    clearInterval(timer);
    process.exit(0);
    return;
  }

  // Big gap == the machine (and this process) was asleep. Reset the
  // grace window so we don't false-positive on the inflated heartbeat age.
  if (gap > WAKE_GAP_MS) {
    log("wake detected (tick gap " + gap + "ms) -> resetting grace window");
    lastValue = readHeartbeat();
    unchangedSince = now;
    return;
  }

  const cur = readHeartbeat();
  if (cur !== lastValue) {
    lastValue = cur;
    unchangedSince = now;
    return;
  }

  if (now - unchangedSince >= STALE_MS && !recovering) {
    recovering = true;
    log("MAIN WEDGED: heartbeat frozen at '" + cur + "' for " +
        (now - unchangedSince) + "ms of awake time; SIGKILL pid " +
        MAIN_PID + " + relaunch");
    try { process.kill(MAIN_PID, "SIGKILL"); } catch (e) { log("kill failed: " + e); }
    setTimeout(function () {
      relaunch();
      clearInterval(timer);
      process.exit(0);
    }, 1500);
  }
}, TICK_MS);
// Intentionally NOT unref'd — the watchdog must stay alive on its own.
`;

/**
 * Spawn the external watchdog. Idempotent. Call once at boot, after the
 * file logger has initialised (it owns the heartbeat path). No-op in dev
 * (the packaged .app path we'd relaunch doesn't exist) unless
 * AVA_ENABLE_WATCHDOG=1 is set for testing.
 */
export function startWatchdog(): void {
  if (started) return;
  started = true;

  if (!app.isPackaged && process.env.AVA_ENABLE_WATCHDOG !== "1") {
    console.log("[watchdog] skipped (dev mode; set AVA_ENABLE_WATCHDOG=1 to test)");
    return;
  }

  try {
    const userData = app.getPath("userData");
    mkdirSync(userData, { recursive: true });
    const scriptPath = join(userData, "ava-watchdog.cjs");
    writeFileSync(scriptPath, WATCHDOG_SOURCE, "utf8");

    // v0.1.351 — Stale Update-Flag eines abgebrochenen Updates beim
    // Boot räumen, sonst würde der frische Watchdog sich sofort wieder
    // beenden. Wenn wir hier (neu) starten, ist kein Update aktiv.
    try {
      rmSync(getUpdatingFlagPath(), { force: true });
    } catch {
      /* ignore */
    }

    const child = spawn(process.execPath, [scriptPath], {
      detached: true,
      stdio: "ignore",
      env: {
        ...process.env,
        ELECTRON_RUN_AS_NODE: "1",
        AVA_WD_HEARTBEAT: getHeartbeatPath(),
        AVA_WD_MAIN_PID: String(process.pid),
        AVA_WD_APP_PATH: appBundlePath(),
        AVA_WD_LOG: join(getLogDir(), "ava-watchdog.log"),
        AVA_WD_UPDATING_FLAG: getUpdatingFlagPath(),
      },
    });
    child.unref();
    console.log(
      `[watchdog] spawned external watchdog pid=${child.pid ?? "?"} -> ${scriptPath}`,
    );
  } catch (err) {
    console.warn(
      "[watchdog] failed to spawn:",
      err instanceof Error ? err.message : String(err),
    );
  }
}

/**
 * Resolve the relaunch target. On macOS we want the `.app` bundle (so
 * `open` re-launches a fresh instance), not the inner Mach-O binary.
 */
function appBundlePath(): string {
  const exe = app.getPath("exe");
  if (process.platform === "darwin") {
    const idx = exe.indexOf(".app/");
    if (idx >= 0) return exe.slice(0, idx + 4); // keep through ".app"
  }
  return exe;
}
