#!/usr/bin/env node
//
// v0.1.213 — One-Shot-Sync für vendoriertes `@ava/ai-provider`.
//
// Hintergrund: Die vier Producer-Submodule (`company-profile`,
// `company-contact`, `company-evaluation`, `website`) tragen jeweils
// eine vendorierte Kopie von `@ava/ai-provider` unter
// `<producer>/vendor/ai-provider/`. Sobald jemand etwas am
// Workspace-Paket ändert (z. B. v0.1.210 → neues `pricing.ts`),
// kommt der CI-Drift-Check ins Trudeln, weil die SHA-256 nicht mehr
// passt.
//
// Dieses Skript automatisiert die Resync-Choreografie:
//
//   1. `pnpm -F @ava/ai-provider build` — Canonical neu bauen.
//   2. Per Producer: rsync dist/ + src/ aus dem Workspace-Paket.
//   3. Wenn der Producer-Workdir dirty ist → in dem Submodul
//      committen ("chore(vendor): resync @ava/ai-provider with
//      <parent-version>") und pushen, sodass der Submodul-HEAD
//      bewegt wird.
//   4. Zum Schluss eine Anweisung ausgeben, wie der Parent-Repo den
//      Submodul-Pointer-Bump committen + pushen muss.
//
// Was das Skript NICHT macht:
//   - Es committet NICHT im Parent-Repo selbst. Damit kann der
//     Entwickler die Submodul-Pointer-Bumps zusammen mit dem
//     eigentlichen Feature-Commit oder als Hotfix-Release committen.
//   - Es lädt keine Branches im Parent oder Submodul; läuft auf
//     `HEAD` der bereits ausgecheckten Branch.
//
// Aufruf:
//   pnpm vendor:sync
//
// Pre-Push-Hook (`.githooks/pre-push`) ruft NICHT dieses Skript auf,
// sondern nur den Read-only-`check-vendor-drift.mjs`. Der Hook
// blockt Pushes mit Drift; das Mutieren bleibt explizit beim
// Entwickler.

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");

const PRODUCERS = [
  "company-profile",
  "company-contact",
  "company-evaluation",
  "website",
];

function run(cmd, args, opts = {}) {
  const res = spawnSync(cmd, args, {
    stdio: "inherit",
    cwd: opts.cwd ?? REPO_ROOT,
    env: opts.env ?? process.env,
  });
  if (res.status !== 0) {
    console.error(`\nvendor-sync: ${cmd} ${args.join(" ")} failed (exit ${res.status})`);
    process.exit(res.status ?? 1);
  }
}

function runCapture(cmd, args, opts = {}) {
  const res = spawnSync(cmd, args, {
    cwd: opts.cwd ?? REPO_ROOT,
    env: opts.env ?? process.env,
    encoding: "utf8",
  });
  return { status: res.status ?? 1, stdout: res.stdout ?? "", stderr: res.stderr ?? "" };
}

function parentDesktopVersion() {
  try {
    const pkg = JSON.parse(
      readFileSync(join(REPO_ROOT, "services/desktop/package.json"), "utf8"),
    );
    return typeof pkg.version === "string" ? pkg.version : "unknown";
  } catch {
    return "unknown";
  }
}

// ---- 1. Canonical bauen ----------------------------------------------------

console.log("vendor-sync: building canonical @ava/ai-provider …");
run("pnpm", ["-F", "@ava/ai-provider", "build"]);

const CANONICAL_DIST = join(REPO_ROOT, "packages/ai-provider/dist");
const CANONICAL_SRC = join(REPO_ROOT, "packages/ai-provider/src");
if (!existsSync(CANONICAL_DIST)) {
  console.error(`vendor-sync: ${CANONICAL_DIST} not produced — build broken?`);
  process.exit(1);
}

const desktopVersion = parentDesktopVersion();
const commitMessage =
  `chore(vendor): resync @ava/ai-provider with parent v${desktopVersion}\n\n` +
  `Mechanical rsync of dist/ + src/ from packages/ai-provider/.\n` +
  `Generated by scripts/vendor-sync.mjs.`;

// ---- 2. Resync pro Producer ------------------------------------------------

let resyncedProducers = [];
let unchangedProducers = [];

for (const p of PRODUCERS) {
  const producerRoot = join(REPO_ROOT, p);
  const vendorDir = join(producerRoot, "vendor", "ai-provider");
  if (!existsSync(vendorDir)) {
    console.log(`vendor-sync: ${p} — no vendor/ai-provider/ (skipped)`);
    continue;
  }
  console.log(`\nvendor-sync: → ${p}`);

  // rsync dist + src. `--delete` damit gelöschte Quelldateien auch im
  // vendoring verschwinden (sonst Geisterdateien wie ein altes
  // pricing-stub.ts).
  run("rsync", [
    "-a",
    "--delete",
    join(CANONICAL_DIST, "/"),
    join(vendorDir, "dist") + "/",
  ]);
  run("rsync", [
    "-a",
    "--delete",
    join(CANONICAL_SRC, "/"),
    join(vendorDir, "src") + "/",
  ]);

  // Ist im Submodul-Workdir was passiert?
  const status = runCapture(
    "git",
    ["status", "--porcelain", "vendor/ai-provider"],
    { cwd: producerRoot },
  );
  if (status.stdout.trim().length === 0) {
    console.log(`vendor-sync:   ${p} already up-to-date.`);
    unchangedProducers.push(p);
    continue;
  }

  // Commit + push im Submodul. Wir pushen auf den aktuell ausgecheckten
  // Branch (`HEAD`) — das matched, was die `chore/ai-sdk-migration` /
  // `main`-Konfig aus .gitmodules tatsächlich tracked.
  run("git", ["add", "vendor/ai-provider"], { cwd: producerRoot });
  run("git", ["commit", "-m", commitMessage], { cwd: producerRoot });
  run("git", ["push", "origin", "HEAD"], { cwd: producerRoot });

  resyncedProducers.push(p);
}

// ---- 3. Zusammenfassung + Anweisung für den Parent -------------------------

console.log("");
console.log("vendor-sync: summary");
console.log("--------------------");
for (const p of resyncedProducers) console.log(`  ✓ ${p} — submodule HEAD bumped`);
for (const p of unchangedProducers) console.log(`  · ${p} — already in sync`);

if (resyncedProducers.length === 0) {
  console.log("\nNo submodule changes needed.");
  process.exit(0);
}

console.log("");
console.log("Next steps in the parent repo:");
console.log("");
console.log("  git add " + resyncedProducers.join(" "));
console.log(`  git commit -m "chore: bump producer submodules for ai-provider resync"`);
console.log("  git push");
console.log("");
console.log(
  "If you're rolling a release that includes this resync, bump",
);
console.log(
  "  services/desktop/package.json + tag it after the parent push.",
);
