// Types shared across the main / preload / renderer boundaries.
//
// Each tsconfig project (node vs web) is sealed off from the other, so
// any type that crosses the boundary lives here and gets imported via
// type-only imports on both sides.

export interface AppConfig {
  gatewayUrl: string;
}

export interface AuthStatus {
  signedIn: boolean;
  accessToken: string | null;
  expiresAt: number | null;
  // Decoded for UI display only; gateway re-verifies the JWT signature.
  actorId: string | null;
  tenantId: string | null;
  scopes: string[];
}

// ---- Ollama (D7 — bundled runtime) -----------------------------------------
//
// The desktop app spawns Ollama as a child process. The renderer never talks
// to Ollama directly — it only reads supervisor state via IPC and triggers
// model pulls through IPC. Local LLM/embedding calls go through the
// db-gateway, which itself hits the supervisor's loopback port.

/** Role a model fills in the AVA pipeline (D8 ai-provider factory). */
export type OllamaModelRole = "llm" | "embed";

export interface OllamaModelSpec {
  /** Tag passed to `ollama pull` and used in API calls. */
  name: string;
  role: OllamaModelRole;
  /** Approximate on-disk size for UX progress hints. */
  approxBytes: number;
}

export interface OllamaInstalledModel {
  name: string;
  size: number;
  digest: string;
  modifiedAt: string;
}

/**
 * Lifecycle of the bundled child process.
 *  - `idle`: not started yet (pre-app.whenReady)
 *  - `starting`: spawn in flight, waiting for `/api/tags` 200
 *  - `ready`: server responding, model list fetched at least once
 *  - `error`: spawn failed or health-check timed out (renderer should
 *    show a recovery screen — not a fatal exit, the rest of the app still
 *    works against any cloud-only fallback the gateway permits)
 *  - `stopping`: graceful shutdown in progress
 */
export type OllamaSupervisorState =
  | "idle"
  | "starting"
  | "ready"
  | "error"
  | "stopping";

export interface OllamaStatus {
  state: OllamaSupervisorState;
  /** http URL the child process is listening on, e.g. "http://127.0.0.1:11434". */
  host: string | null;
  /** Required models the supervisor knows about (catalog, not what's installed). */
  required: OllamaModelSpec[];
  /** What Ollama reports as installed. Empty array until first `ready`. */
  installed: OllamaInstalledModel[];
  /** Subset of `required` that is missing from `installed`. */
  missing: OllamaModelSpec[];
  /** Last error message (only set when state === "error"). */
  errorMessage: string | null;
}

/**
 * One frame of pull progress, mirroring the Ollama `/api/pull` stream
 * shape. The supervisor coalesces frames at ~5 Hz before forwarding to
 * renderer to keep IPC traffic bounded.
 */
export interface OllamaPullProgress {
  modelName: string;
  status: string;
  /** When known (during the actual download), bytes pulled so far. */
  completed?: number;
  /** When known, total bytes to pull. */
  total?: number;
  /** True on the final frame for this model. */
  done: boolean;
  /** Set on the final frame iff the pull failed. */
  errorMessage?: string;
}

// ---- Agent (Phase 8) -------------------------------------------------------
//
// The local research agent. Lives in the main process; renderer only sends
// user turns and receives streamed frames over IPC. Memory persists to
// markdown files under `app.getPath("userData")/memory/` (8.d).
//
// Multi-turn conversations are addressed by a `conversationId` (opaque
// string, generated client-side). 8.a only supports one in-flight request
// at a time per orchestrator — a second `send` while one is running rejects.

/** Status snapshot, queried on app boot and after model/Ollama transitions. */
export interface AgentStatus {
  /** True iff the orchestrator can accept a new send (Ollama ready, model picked). */
  ready: boolean;
  /** The Ollama tag the agent will send to /api/chat. Null if no llm-role model. */
  model: string | null;
  /** Mirrors OllamaSupervisor.host — null while the supervisor isn't ready. */
  ollamaHost: string | null;
  /** Set while a send is being processed (single-slot in 8.a). */
  inFlightRequestId: string | null;
  /** Last error message, if the orchestrator is in a sticky-error state. */
  errorMessage: string | null;
  /**
   * Set when the on-disk memory dir (`userData/agent/memory`) failed its
   * boot-time writability probe (Phase 8.d). The agent still functions
   * (in-memory only) but the FirstRunWizard surfaces this so the user
   * knows transcripts won't survive a restart.
   */
  memoryError: string | null;
}

/**
 * One chat turn. Mirrors Ollama /api/chat's role taxonomy plus a `tool`
 * role for tool-call results that the orchestrator feeds back into the
 * model on the next loop iteration.
 *
 * `id` is generated by the orchestrator so the renderer can de-dupe and
 * the markdown log (8.d) can reference messages stably.
 */
export interface AgentMessage {
  id: string;
  role: "system" | "user" | "assistant" | "tool";
  content: string;
  /** Tool calls the assistant decided to make (if any). 8.b+ populates this. */
  toolCalls?: AgentToolCall[];
  /** When role==="tool", which tool call this message answers. */
  toolCallId?: string;
  /** Wall-clock ms since epoch — for log ordering and UI timestamps. */
  createdAt: number;
}

export interface AgentToolCall {
  id: string;
  name: string;
  /** Already-validated arguments. The orchestrator runs yup on the raw args
   *  before populating this; if validation fails the orchestrator emits an
   *  error frame instead of executing. */
  args: unknown;
}

export interface AgentSendInput {
  conversationId: string;
  /** User-typed text. */
  message: string;
}

export interface AgentSendResult {
  requestId: string;
}

/**
 * One option in an `ask_user_choice` prompt (8.c). `value` is the stable
 * machine-readable token the agent gets back; `label` is what the user
 * sees on the button.
 */
export interface AgentChoiceOption {
  value: string;
  label: string;
  /** Optional secondary text rendered under the label. */
  description?: string;
}

/**
 * Streaming frame multiplexed over a single IPC channel. The renderer
 * filters by `requestId` (8.a uses one request at a time, but the protocol
 * is future-proof for parallel runs).
 *
 * Frame types:
 *  - `token`           — content delta from the assistant. Concatenate to render.
 *  - `tool-call`       — assistant decided to call a tool (preview before run).
 *  - `tool-result`     — tool finished; carries the result preview.
 *  - `choice-request`  — UI tool asks the user to pick an option (8.c).
 *                        Renderer answers via `window.api.agent.answerChoice`.
 *  - `choice-resolved` — emitted after the user picked, so other windows /
 *                        replays know the prompt is closed.
 *  - `navigate`        — UI tool tells the renderer to route somewhere (8.c).
 *  - `error`           — terminal; the request is aborted.
 *  - `done`            — terminal; the assistant finished its turn cleanly.
 */
export type AgentStreamFrame =
  | { kind: "token"; requestId: string; conversationId: string; messageId: string; delta: string }
  | { kind: "tool-call"; requestId: string; conversationId: string; toolCall: AgentToolCall }
  | { kind: "tool-result"; requestId: string; conversationId: string; toolCallId: string; ok: boolean; preview: string }
  | {
      kind: "choice-request";
      requestId: string;
      conversationId: string;
      choiceId: string;
      prompt: string;
      options: AgentChoiceOption[];
    }
  | {
      kind: "choice-resolved";
      requestId: string;
      conversationId: string;
      choiceId: string;
      value: string;
    }
  | { kind: "navigate"; requestId: string; conversationId: string; path: string }
  | { kind: "error"; requestId: string; conversationId: string; message: string }
  | { kind: "done"; requestId: string; conversationId: string; messageId: string };

/** Renderer → main. Resolves a pending `choice-request`. */
export interface AgentChoiceAnswer {
  choiceId: string;
  value: string;
}

// ---- Provider switch (Phase 8.j + 8.k) -------------------------------------
//
// The agent runs against one of five providers, three of which require an
// API key. The selection persists in `userData/agent/provider.json`; each
// hosted provider's key is encrypted via Electron's `safeStorage` and
// lives in `userData/agent/<provider>.enc`.
//
// Providers wrapped via Vercel AI SDK through `@ava/ai-provider` (Phase
// 8.k1). Adding a sixth provider means: pick its model from the shared
// catalog, add a kind below, add a `runtime.ts` branch in ai-provider —
// no orchestrator or UI changes.

export type LlmProviderKind =
  | "ollama"
  | "openai"
  | "anthropic"
  | "google"
  | "mistral";

/** Subset that requires an API key — used by the key-storage UIs. */
export type HostedProviderKind = Exclude<LlmProviderKind, "ollama">;

export interface ProviderConfig {
  /** Currently active provider for new turns. */
  kind: LlmProviderKind;
  /**
   * Selected model id per provider. Always present so flipping providers
   * doesn't drop the user's prior model choice. Empty string for a kind
   * means "use catalog recommendation".
   */
  models: Record<LlmProviderKind, string>;
}

export interface ProviderStatusSnapshot {
  kind: LlmProviderKind;
  model: string | null;
  ready: boolean;
  errorMessage: string | null;
}

export interface ProviderConfigBundle {
  config: ProviderConfig;
  status: ProviderStatusSnapshot;
  /** Per-provider key presence. ollama is always `true` (no key needed). */
  hasKey: Record<LlmProviderKind, boolean>;
  encryptionAvailable: boolean;
}

/**
 * Catalog entry projected over IPC for the renderer's model picker.
 * Mirrors `CatalogEntry` from `@ava/ai-provider/catalog` but stays a
 * plain JSON shape so the renderer doesn't import the package directly.
 */
export interface ProviderCatalogEntry {
  provider: LlmProviderKind;
  id: string;
  label: string;
  /**
   * Capabilities the agent picker filters on. The shared catalog tracks
   * more (vision, embedding dimensions, …) but the desktop only needs
   * "can I use this for the chat agent".
   */
  tools: boolean;
  vision: boolean;
  contextWindow: number;
  costClass: "free" | "cheap" | "mid" | "high";
  recommended: boolean;
  /** Approximate on-disk size for Ollama tags — UX hint only. */
  approxBytes?: number;
}
